# Generated by Django 5.1.7 on 2025-05-03 18:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoAreaMapping",
            fields=[
                (
                    "geo_area",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(max_length=255)),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                ("area_km2", models.FloatField()),
                ("built_up_area_km2", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        default=django.contrib.gis.geos.collections.MultiPolygon(),
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "geo_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.geoareamapping",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("walk", "Walkability"), ("bike", "Bikeability")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "type")},
            },
        ),
        migrations.CreateModel(
            name="MetricValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("datetime", models.DateTimeField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="streets.city"
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="streets.metric"
                    ),
                ),
            ],
            options={
                "unique_together": {("metric", "city", "datetime")},
            },
        ),
    ]
