# Generated by Django 5.1.7 on 2025-04-25 15:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("area_km2", models.FloatField()),
                ("built_up_area_km2", models.FloatField()),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="GeoAreaMapping",
            fields=[
                (
                    "geo_area",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("osm_u", models.BigIntegerField()),
                ("osm_v", models.BigIntegerField()),
                ("osm_key", models.IntegerField(default=0)),
                ("is_pedestrian", models.BooleanField(default=False)),
                ("is_cycling", models.BooleanField(default=False)),
                ("is_driving", models.BooleanField(default=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "osm_u", "osm_v", "osm_key")},
            },
        ),
        migrations.AddField(
            model_name="city",
            name="geo_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="streets.geoareamapping"
            ),
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("elevation", models.FloatField()),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.city",
                        verbose_name="City",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EdgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.edge",
                        verbose_name="Edge",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.node",
                        verbose_name="Node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CityAccessibilityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("walkability", "Walkability"),
                            ("bikeability", "Bikeability"),
                        ],
                        max_length=20,
                    ),
                ),
                ("POP", models.IntegerField()),
                ("CIR", models.FloatField()),
                ("ORE", models.FloatField()),
                ("RDE", models.FloatField()),
                ("AST", models.FloatField()),
                ("ASL", models.FloatField()),
                ("IND", models.FloatField()),
                ("BDR", models.FloatField()),
                ("ABS", models.FloatField()),
                ("ACO", models.FloatField()),
                ("SCO", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "type")},
            },
        ),
    ]
