# Generated by Django 5.1.7 on 2025-04-25 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="edge",
            name="osm_key",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="osm_u",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="osm_v",
        ),
    ]
