# Generated by Django 5.1.7 on 2025-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0002_alter_edge_unique_together_remove_edge_osm_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
