# Generated by Django 5.1.7 on 2025-05-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0003_alter_node_elevation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="end_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_edges",
                to="streets.node",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="start_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_edges",
                to="streets.node",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("city", "start_node", "end_node"), name="unique_edge_in_city"
            ),
        ),
    ]
