# Generated by Django 5.1.7 on 2025-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0003_alter_edge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="speed_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edge",
            name="street_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
