# Generated by Django 5.1.7 on 2025-04-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0004_edge_speed_limit_edge_street_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityBikeabilityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("POP", models.IntegerField()),
                ("CIR", models.FloatField()),
                ("ORE", models.FloatField()),
                ("RDE", models.FloatField()),
                ("AST", models.FloatField()),
                ("ASL", models.FloatField()),
                ("IND", models.FloatField()),
                ("BDR", models.FloatField()),
                ("ABS", models.FloatField()),
                ("ACO", models.FloatField()),
                ("SCO", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "unique_together": {("city",)},
            },
        ),
        migrations.CreateModel(
            name="CityWalkabilityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("POP", models.IntegerField()),
                ("CIR", models.FloatField()),
                ("ORE", models.FloatField()),
                ("RDE", models.FloatField()),
                ("AST", models.FloatField()),
                ("ASL", models.FloatField()),
                ("IND", models.FloatField()),
                ("WDR", models.FloatField()),
                ("AWS", models.FloatField()),
                ("ACO", models.FloatField()),
                ("SCO", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streets.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "unique_together": {("city",)},
            },
        ),
        migrations.DeleteModel(
            name="CityAccessibilityMetrics",
        ),
    ]
