# Generated by Django 5.1.7 on 2025-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0004_alter_edge_end_node_alter_edge_start_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="osm_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
