# Generated by Django 5.1.7 on 2025-05-08 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0005_node_osm_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="data",
        ),
    ]
