# Generated by Django 5.1.7 on 2025-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0006_remove_edge_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="elevation",
        ),
        migrations.RemoveField(
            model_name="node",
            name="id",
        ),
        migrations.AlterField(
            model_name="node",
            name="osm_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
