# Generated by Django 5.1.7 on 2025-04-26 13:21

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0007_update_geom_to_multipolygon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                default=django.contrib.gis.geos.collections.MultiPolygon(),
                null=True,
                srid=4326,
            ),
        ),
    ]
