# Generated by Django 5.1.7 on 2025-05-12 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0007_remove_node_elevation_remove_node_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="area_km2",
        ),
        migrations.RemoveField(
            model_name="city",
            name="built_up_area_km2",
        ),
        migrations.RemoveField(
            model_name="city",
            name="geom",
        ),
        migrations.RemoveField(
            model_name="city",
            name="population",
        ),
    ]
