# Generated by Django 5.1.7 on 2025-05-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streets", "0008_remove_city_area_km2_remove_city_built_up_area_km2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="type",
            field=models.CharField(
                choices=[
                    ("walk", "Walkability"),
                    ("bike", "Bikeability"),
                    ("drive", "Drivability"),
                ],
                max_length=10,
            ),
        ),
    ]
